<a href="https://colab.research.google.com/github/brijesh2004/ML-/blob/main/02_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy - Numerical Python


Advantages of Numpy Arrays

   1 . Allows several Mathematical Operations
    
   2 . Faster operations

In [1]:
import numpy as np

List vs Numpy - Time take

In [2]:
from time import process_time

Time taken by a list

In [3]:
python_list = [i for i in range(10000)]

start_time = process_time()
python_list = [i+5 for i in python_list]
end_time = process_time()

print(end_time-start_time)


0.0010014100000006465


Numpy array

In [4]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5 # add 5 to all the element of the numpy array
end_time = process_time()

print(end_time-start_time)


0.0016365120000001454


Numpy Array

In [5]:
#list
list1 = [1,2,3,4,5]
print(list1)
print(type(list1))

[1, 2, 3, 4, 5]
<class 'list'>


In [6]:
np_array = np.array([1,2,3,4,5])

print(np_array)

print(type(np_array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [7]:
# creating a 1 dim array
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [8]:
a.shape

(4,)

In [9]:
b = np.array([(1,2,3,4),(5,6,7,8)])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
b.shape


(2, 4)

In [11]:
c = np.array([(1,2,3,4),(5,6,7,8)] , dtype=float)
c

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

Initial Placeholder in numpy array

In [12]:
# create a numpy array of zeros
x = np.zeros((4,5))
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
# create a numpy arrays of one
y = np.ones((3,3))
y

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
# array of a particular value

z = np.full((5,4), 5)   # first (5,4) for the dimension of the array and the second is for the value for array
z

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [16]:
# create an identity matrix

a = np.eye(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
# create a numpy array with random value
b = np.random.random((3,4))
b

array([[0.83278841, 0.51488569, 0.43969025, 0.32619713],
       [0.05113941, 0.57954862, 0.95918386, 0.57815335],
       [0.99666877, 0.52499875, 0.00720157, 0.51483927]])

In [19]:
# random integer values array within a specific range
c= np.random.randint(10,100 , (3,5))
c

array([[47, 36, 17, 76, 50],
       [91, 48, 41, 31, 94],
       [74, 29, 13, 84, 26]])

In [20]:
c= np.random.randint(10,13 , (3,5))
c

array([[11, 10, 12, 10, 11],
       [11, 10, 11, 10, 12],
       [12, 11, 12, 12, 10]])

In [21]:
# array of evenly spaced value -- specify the number of value required
d = np.linspace(10 , 30,5)
d

array([10., 15., 20., 25., 30.])

In [22]:
# array of evenly spaced value  -- specifying the step
e = np.arange(10,30,5)
e

array([10, 15, 20, 25])

In [24]:
e = np.arange(10,101,5)
e

array([ 10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,  70,
        75,  80,  85,  90,  95, 100])

In [26]:
# converting a list to a numpy array

list2 = [10 ,20,20,20,50]

np_array = np.array(list2)
print(np_array)
print(type(np_array))

[10 20 20 20 50]
<class 'numpy.ndarray'>


Analysing a numpy array

In [27]:
c = np.random.randint(10,90,(5,5))
c

array([[43, 83, 73, 68, 39],
       [69, 68, 31, 26, 27],
       [79, 28, 18, 76, 40],
       [64, 29, 32, 33, 14],
       [68, 36, 88, 42, 51]])

In [28]:
# array dimension
print(c.shape)

(5, 5)


In [29]:
# number of dimensions
c.ndim

2

In [30]:
#number of element in an array
c.size


25

In [31]:
# checking the data type of the values in array
c.dtype

dtype('int64')

Mathematical Operations on a np array

In [32]:
list1 = [1,2,3,4,5]
list2 = [5,6,7,8,9]
list1+list2 # concatenate or join the list

[1, 2, 3, 4, 5, 5, 6, 7, 8, 9]

In [33]:
a = np.random.randint(0,10 , (3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)

[[9 2 1]
 [7 3 0]
 [5 3 4]]
[[18 19 16]
 [14 11 11]
 [15 17 17]]


In [35]:
print(a+b) # element wise addition
print(a-b)
print(a*b)
print(a/b)

[[27 21 17]
 [21 14 11]
 [20 20 21]]
[[ -9 -17 -15]
 [ -7  -8 -11]
 [-10 -14 -13]]
[[162  38  16]
 [ 98  33   0]
 [ 75  51  68]]
[[0.5        0.10526316 0.0625    ]
 [0.5        0.27272727 0.        ]
 [0.33333333 0.17647059 0.23529412]]


In [36]:
print(np.add(a ,b))

[[27 21 17]
 [21 14 11]
 [20 20 21]]


In [37]:
print(np.subtract(a,b))

[[ -9 -17 -15]
 [ -7  -8 -11]
 [-10 -14 -13]]


In [39]:
print(np.multiply(a,b))

[[162  38  16]
 [ 98  33   0]
 [ 75  51  68]]


In [40]:
np.divide(a,b)

array([[0.5       , 0.10526316, 0.0625    ],
       [0.5       , 0.27272727, 0.        ],
       [0.33333333, 0.17647059, 0.23529412]])

Array Manipulation

In [41]:
array = np.random.randint(0,10,(2,3))

In [42]:
array

array([[6, 5, 2],
       [1, 4, 0]])

In [43]:
array.shape

(2, 3)

In [44]:
np.transpose(array)


array([[6, 1],
       [5, 4],
       [2, 0]])

In [45]:
array.T   # transponse of the matrix

array([[6, 1],
       [5, 4],
       [2, 0]])

In [48]:
# reshaping array
b = array.reshape(3,2)
b

array([[6, 5],
       [2, 1],
       [4, 0]])